INSERT INTO Team (idTeam, teamName, teamNationality) VALUES 
(1, 'Ferrari', 'Italian'),
(2, 'Force India', 'Indian'),
(3, 'HRT', 'Spanish'),
(4, 'Lotus', 'Malaysian'),
(5, 'McLaren', 'British'),
(6, 'Mercedes', 'German'),
(7, 'Red Bull', 'Austrian'),
(8, 'Renault', 'French'),
(9, 'Sauber', 'Swiss'),
(10, 'Toro Rosso', 'Italian'),
(11, 'Virgin', 'British'),
(12, 'Williams', 'British'),
(13, 'Caterham', 'Malaysian'),
(14, 'Lotus F1', 'British'),
(15, 'Marussia', 'Russian'),
(16, 'Manor Marussia', 'British'),
(17, 'Haas F1 Team', 'American'),
(18, 'Alfa Romeo', 'Swiss'),
(19, 'Racing Point', 'British'),
(20, 'AlphaTauri', 'Italian'),
(21, 'Alpine F1 Team', 'French'),
(22, 'Aston Martin', 'British'),
(23, 'RB F1 Team', 'Italian')